#!/bin/bash
#
# Interactive setup script for workspace-auth-middleware testing
#
# This script helps you configure the required environment variables
# for testing with real Google Cloud credentials.
#

set -e

echo "======================================================================"
echo "Workspace Auth Middleware - Environment Setup"
echo "======================================================================"
echo ""
echo "This script will help you configure environment variables for testing"
echo "with real Google Cloud credentials."
echo ""

# Function to read user input with default value
read_with_default() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"

    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        value="${value:-$default}"
    else
        read -p "$prompt: " value
    fi

    echo "$value"
}

# Check if .env file exists
if [ -f .env ]; then
    echo "Found existing .env file. Loading current values..."
    source .env 2>/dev/null || true
    echo ""
fi

echo "----------------------------------------------------------------------"
echo "Step 1: Google OAuth2 Client ID (REQUIRED)"
echo "----------------------------------------------------------------------"
echo "Get this from: https://console.cloud.google.com/apis/credentials"
echo "Type: OAuth 2.0 Client ID (Web application)"
echo ""

GOOGLE_CLIENT_ID=$(read_with_default "Enter your OAuth2 Client ID" "$GOOGLE_CLIENT_ID" "GOOGLE_CLIENT_ID")

echo ""
echo "----------------------------------------------------------------------"
echo "Step 2: Google Workspace Domain (RECOMMENDED)"
echo "----------------------------------------------------------------------"
echo "This restricts authentication to users from your workspace."
echo "Example: 'example.com' or 'mycompany.org'"
echo ""

GOOGLE_WORKSPACE_DOMAIN=$(read_with_default "Enter your workspace domain (or press Enter to skip)" "$GOOGLE_WORKSPACE_DOMAIN" "GOOGLE_WORKSPACE_DOMAIN")

echo ""
echo "----------------------------------------------------------------------"
echo "Step 3: Group Fetching"
echo "----------------------------------------------------------------------"
echo "Do you want to enable group-based authorization? (y/n)"
echo ""

read -p "Enable group fetching? [y/N]: " enable_groups
enable_groups="${enable_groups:-n}"

if [[ "$enable_groups" =~ ^[Yy]$ ]]; then
    FETCH_GROUPS="true"

    echo ""
    echo "Group fetching requires a service account with domain-wide delegation."
    echo ""
    echo "Step 3a: Service Account Credentials"
    echo ""

    GOOGLE_APPLICATION_CREDENTIALS=$(read_with_default "Enter path to service account JSON key" "$GOOGLE_APPLICATION_CREDENTIALS" "GOOGLE_APPLICATION_CREDENTIALS")

    echo ""
    echo "Step 3b: Delegated Admin Email"
    echo "This should be an admin user in your Google Workspace."
    echo ""

    GOOGLE_DELEGATED_ADMIN=$(read_with_default "Enter delegated admin email" "$GOOGLE_DELEGATED_ADMIN" "GOOGLE_DELEGATED_ADMIN")
else
    FETCH_GROUPS="false"
    echo "Group fetching disabled."
fi

echo ""
echo "----------------------------------------------------------------------"
echo "Step 4: Test User (Optional - for integration tests)"
echo "----------------------------------------------------------------------"
echo ""

TEST_USER_EMAIL=$(read_with_default "Enter test user email (or press Enter to skip)" "$TEST_USER_EMAIL" "TEST_USER_EMAIL")

echo ""
echo "======================================================================"
echo "Configuration Summary"
echo "======================================================================"
echo ""
echo "GOOGLE_CLIENT_ID:              $GOOGLE_CLIENT_ID"
echo "GOOGLE_WORKSPACE_DOMAIN:       ${GOOGLE_WORKSPACE_DOMAIN:-<not set>}"
echo "FETCH_GROUPS:                  $FETCH_GROUPS"

if [ "$FETCH_GROUPS" = "true" ]; then
    echo "GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-<not set>}"
    echo "GOOGLE_DELEGATED_ADMIN:        ${GOOGLE_DELEGATED_ADMIN:-<not set>}"
fi

echo "TEST_USER_EMAIL:               ${TEST_USER_EMAIL:-<not set>}"
echo ""

read -p "Save this configuration? [Y/n]: " save_config
save_config="${save_config:-y}"

if [[ "$save_config" =~ ^[Yy]$ ]]; then
    # Write to .env file
    cat > .env << EOF
# Generated by setup_env.sh on $(date)
# Workspace Auth Middleware Configuration

# Required: OAuth2 Client ID
export GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID"

# Recommended: Workspace domain
export GOOGLE_WORKSPACE_DOMAIN="$GOOGLE_WORKSPACE_DOMAIN"

# Group fetching
export FETCH_GROUPS="$FETCH_GROUPS"
EOF

    if [ "$FETCH_GROUPS" = "true" ]; then
        cat >> .env << EOF

# Service account credentials (for group fetching)
export GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS"

# Delegated admin email
export GOOGLE_DELEGATED_ADMIN="$GOOGLE_DELEGATED_ADMIN"
EOF
    fi

    if [ -n "$TEST_USER_EMAIL" ]; then
        cat >> .env << EOF

# Test user (for integration tests)
export TEST_USER_EMAIL="$TEST_USER_EMAIL"
EOF
    fi

    echo ""
    echo "Configuration saved to .env"
    echo ""
    echo "To use this configuration, run:"
    echo "  source .env"
    echo ""
    echo "Or add it to your shell profile (~/.bashrc or ~/.zshrc):"
    echo "  echo 'source $(pwd)/.env' >> ~/.bashrc"
    echo ""
else
    echo "Configuration not saved."
fi

echo "======================================================================"
echo "Next Steps"
echo "======================================================================"
echo ""
echo "1. Load the environment variables:"
echo "   $ source .env"
echo ""
echo "2. Get a Google ID token:"
echo "   $ TOKEN=\$(gcloud auth print-identity-token)"
echo ""
echo "3. Run the test server:"
echo "   $ poetry run python examples/manual_testing.py"
echo ""
echo "4. Test the API:"
echo "   $ curl -H \"Authorization: Bearer \$TOKEN\" http://localhost:8000/me"
echo ""
echo "5. (Optional) Run integration tests:"
echo "   $ export RUN_INTEGRATION_TESTS=true"
echo "   $ poetry run pytest tests/test_integration_adc.py -v"
echo ""
echo "======================================================================"
