# yamllint disable rule:line-length
---
name: Build Wheel

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'
    tags:
      - '*'
  schedule:
    - cron: '0 8 1,15 * *'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run PyTest
        run: |
          poetry run pytest tests/

      - name: Run Ruff
        run: |
          poetry run ruff check workspace_auth_middleware

      - name: Run MyPy
        run: |
          poetry run mypy workspace_auth_middleware

  build_package:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Build the project
        run: |
          bash build_wheels.sh

      - name: Upload Python Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: dist/

  upload_package:
    needs: build_package
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-tags: true

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifacts
          path: dist/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Deployment Branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: deployment
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_package:
    needs: build_package
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-tags: true

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifacts
          path: dist/

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Upload to GCP
        run: |
          poetry version $(git describe --tags --long | sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+)-([0-9]+)-g[0-9a-f]+$/\1a\2/')

          poetry config http-basic.data-systems-artifact-repository oauth2accesstoken "$(gcloud auth print-access-token)"

          poetry publish -r data-systems-artifact-repository --skip-existing
